server:
  port: 8090
  servlet.context-path: /hystrixClient
  tomcat.max-threads: 30

spring.application.name: hystrixClient

customer:
  contractsUri: 'localhost:8091/CustomerContracts/{userId}/getCustomerContracts'
  invoicesUri:  'localhost:8092/CustomerInvoices/{userId}/getCustomerInvoices'