server:
  port: 8090
  servlet.context-path: /HystrixClient
  tomcat.max-threads: 100

spring.application.name: HystrixClient

customer:
  contractsUri: 'http://localhost:8091/CustomerContracts/{userId}/getCustomerContracts'
  invoicesUri:  'http://localhost:8092/CustomerInvoices/{userId}/getCustomerInvoices'


hystrix:
  threadpool.default:
    coreSize: 200
  command.default:
    execution.isolation.thread.timeoutInMilliseconds: 20000
    circuitBreaker.errorThresholdPercentage : 20

management.endpoints.web.exposure.include: hystrix.stream, info, health